language: go
go:
- 1.9.x
before_script:
- curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
script:
- dep ensure
- go test ./...
before_deploy:
- sudo apt-get install ruby ruby-dev build-essential rpm
- gem install --no-ri --no-rdoc fpm
- make build VERSION=`echo ${TRAVIS_TAG//v/}`
deploy:
  provider: releases
  api-key:
    secure: mAACcVnh0keFh5t/KnW/zxMpPqLK/oKFAIkT+EGApnUGsPXajNPSiH+6IRNrJ3I0E2VgRPfPhz2X35wwDctoPd7I4sEx7+Wr4KCqQss5EuwTafhAAioj6YkY5VjT9LG4/EZyC8/1C1ZeHB+FVdy0a/TlgyAeKCPuaqMdfo4GbkIUSpnIHDLOz7zReBPP7jELvUFv+5AOrL95VUGmQtGcdc7T+S76W506x53PO4+V6I55ooo8UARku/GPcXJrZFbH2dU5k596XTJPh40GD3vr8Nwww30XCpFbneCFDwJedvydvVNZ8HPGJeaQBzY/8HiQQGuO8K02WUokU5xQ2yvkBc5deh/SPzkl3ohRboaOE6NSUvzSC6hq5hcw8sbXCHFKSYleqZidTMK4DTfy/1HjwBYpsC0GWzA0BJljZmX6Ol8DjETPQOYgZIZcs4uF3uE0upvdPcjQ8nD/n+p5v/RU+E3ZAilFC8IMtjgDdbarfij3cJgMkOWES9SjNlz/AmHMFE7Oyo1qznMxbjjdEzPOiEmUHGFnHUu6nzlXQDj3iq6FAWq3GurqoR0Bm9tE2D9eNbZm5Adom9tMZ+9pvMMmhUlSkZ1GtJpakzGE/bejB6rpaPIwqZTDDJxiW3v6kZWrCDkecXQuAv3sdtihgjG5m5LsppWuNDclxbQHIYGU31k=
  file_glob: true
  file: build/*
  skip_cleanup: true
  on:
    tags: true
    condition: $TRAVIS_TAG =~ ^v[0-9]+.[0-9]+.[0-9]+$
